---
title: "Fitting an Edge Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{edge_models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(bisonR)
```

```{r}
sim_data <- simulate_edge_model("binary", aggregated=F)
df <- sim_data
head(df)
```

```{r}
priors <- get_default_priors("binary")
priors
```

```{r}
priors$fixed <- "normal(0, 1)"
priors
```

```{r}
fit_edge <- edge_model((event | duration) ~ dyad(node_1_id, node_2_id), data=df, data_type="binary", priors=priors)
```

```{r}
plot_trace(fit_edge)
```

```{r}
summary(fit_edge) # 0.810 -0.051  1.740 
```

```{r}
plot_network(fit_edge, lwd=2)
```

```{r}
plot_predictions(fit_edge, num_draws=20)
```

```{r}
priors <- get_default_priors("dyadic_regression")
priors$error <- "half-normal(2.5)"
```

```{r}
df_dyadic <- df %>%
  distinct(node_1_id, node_2_id, age_diff)

fit_dyadic <- dyadic_regression(dyad(node_1_id, node_2_id) ~ age_diff, fit_edge, df_dyadic, mm=FALSE, priors=priors)
```

```{r}

```
