---
title: "Running a nodal regression"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nodal_regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
cmdstanr::install_cmdstan(cores = 4)
```

```{r}
library(bisonR)
library(tidyverse)
```

```{r}
data("binary_ex1")
df <- binary_ex1
head(df)
```

```{r}
fit_edge <- edge_model((event | 1) ~ dyad(node_1, node_2), data=df, data_type="binary", mc_cores=4, verbose=TRUE)
```

```{r}
df_reg <- data.frame(
  node = as.factor(c("Rey", "Leia", "Obi-Wan", "Luke", "C-3PO", "BB-8", "R2-D2", "D-O")),
  node_type = as.factor(c("Lifeform", "Lifeform", "Lifeform", "Lifeform", "Droid", "Droid", "Droid", "Droid"))
)
df_reg
```

```{r}
fit_node <- nodal_regression(strength(node_names) ~ node_type, fit_edge, df_reg)
```

```{r}
summary(fit_node)
```

```{r}
plot_trace(fit_node)
```

```{r}
plot_predictions(fit_node, num_draws=20)
```

```{r}
get_contrasts(fit_node, "fixed_node_typeLifeform", "fixed_node_typeDroid")
```
