---
title: "Running a nodal regression"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dyadic_regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bisonR)
library(tidyverse)
```

```{r}
data("binary_ex1")
df <- binary_ex1
head(df)
```

```{r}
fit_edge_1 <- edge_model((event | 1) ~ dyad(node_1, node_2), data=df, data_type="binary", method="mcmc", mc_cores=4, verbose=TRUE)
```

```{r}
summary(fit_edge_1)
```

```{r}
fit_edge_0 <- edge_model((event | 1) ~ 1, data=df, data_type="binary", method="mcmc", mc_cores=4, verbose=TRUE)
summary(fit_edge_0)
```

```{r}
formula <- (event | duration) ~ dyad(sender, node_2) + age + sex + (1 | location) + (1 | group)
get_edge_model_spec(formula)
```

```{r}
plot_trace(fit_node)
```

```{r}
plot_predictions(fit_node, num_draws=20)
```

```{r}
get_contrasts(fit_node, "fixed_node_typeLifeform", "fixed_node_typeDroid")
```
