// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_nodal_regression_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_nodal_regression");
    reader.add_event(30, 28, "end", "model_nodal_regression");
    return reader;
}
#include <stan_meta_header.hpp>
class model_nodal_regression
  : public stan::model::model_base_crtp<model_nodal_regression> {
private:
        int num_nodes;
        int num_fixed;
        vector_d centrality_mu;
        matrix_d centrality_cov;
        matrix_d design_fixed;
public:
    model_nodal_regression(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_nodal_regression(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_nodal_regression_namespace::model_nodal_regression";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "num_nodes", "int", context__.to_vec());
            num_nodes = int(0);
            vals_i__ = context__.vals_i("num_nodes");
            pos__ = 0;
            num_nodes = vals_i__[pos__++];
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "num_fixed", "int", context__.to_vec());
            num_fixed = int(0);
            vals_i__ = context__.vals_i("num_fixed");
            pos__ = 0;
            num_fixed = vals_i__[pos__++];
            current_statement_begin__ = 4;
            validate_non_negative_index("centrality_mu", "num_nodes", num_nodes);
            context__.validate_dims("data initialization", "centrality_mu", "vector_d", context__.to_vec(num_nodes));
            centrality_mu = Eigen::Matrix<double, Eigen::Dynamic, 1>(num_nodes);
            vals_r__ = context__.vals_r("centrality_mu");
            pos__ = 0;
            size_t centrality_mu_j_1_max__ = num_nodes;
            for (size_t j_1__ = 0; j_1__ < centrality_mu_j_1_max__; ++j_1__) {
                centrality_mu(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 5;
            validate_non_negative_index("centrality_cov", "num_nodes", num_nodes);
            validate_non_negative_index("centrality_cov", "num_nodes", num_nodes);
            context__.validate_dims("data initialization", "centrality_cov", "matrix_d", context__.to_vec(num_nodes,num_nodes));
            centrality_cov = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(num_nodes, num_nodes);
            vals_r__ = context__.vals_r("centrality_cov");
            pos__ = 0;
            size_t centrality_cov_j_2_max__ = num_nodes;
            size_t centrality_cov_j_1_max__ = num_nodes;
            for (size_t j_2__ = 0; j_2__ < centrality_cov_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < centrality_cov_j_1_max__; ++j_1__) {
                    centrality_cov(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 6;
            validate_non_negative_index("design_fixed", "num_nodes", num_nodes);
            validate_non_negative_index("design_fixed", "num_fixed", num_fixed);
            context__.validate_dims("data initialization", "design_fixed", "matrix_d", context__.to_vec(num_nodes,num_fixed));
            design_fixed = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(num_nodes, num_fixed);
            vals_r__ = context__.vals_r("design_fixed");
            pos__ = 0;
            size_t design_fixed_j_2_max__ = num_fixed;
            size_t design_fixed_j_1_max__ = num_nodes;
            for (size_t j_2__ = 0; j_2__ < design_fixed_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < design_fixed_j_1_max__; ++j_1__) {
                    design_fixed(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 10;
            validate_non_negative_index("beta_fixed", "num_fixed", num_fixed);
            num_params_r__ += num_fixed;
            current_statement_begin__ = 11;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_nodal_regression() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 10;
        if (!(context__.contains_r("beta_fixed")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_fixed missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_fixed");
        pos__ = 0U;
        validate_non_negative_index("beta_fixed", "num_fixed", num_fixed);
        context__.validate_dims("parameter initialization", "beta_fixed", "vector_d", context__.to_vec(num_fixed));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_fixed(num_fixed);
        size_t beta_fixed_j_1_max__ = num_fixed;
        for (size_t j_1__ = 0; j_1__ < beta_fixed_j_1_max__; ++j_1__) {
            beta_fixed(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_fixed);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_fixed: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 11;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 10;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_fixed;
            (void) beta_fixed;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_fixed = in__.vector_constrain(num_fixed, lp__);
            else
                beta_fixed = in__.vector_constrain(num_fixed);
            current_statement_begin__ = 11;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 15;
            validate_non_negative_index("predictor", "num_nodes", num_nodes);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> predictor(num_nodes);
            stan::math::initialize(predictor, DUMMY_VAR__);
            stan::math::fill(predictor, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 16;
            stan::math::assign(predictor, multiply(design_fixed, beta_fixed));
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 15;
            size_t predictor_j_1_max__ = num_nodes;
            for (size_t j_1__ = 0; j_1__ < predictor_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(predictor(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: predictor" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable predictor: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 20;
            lp_accum__.add(multi_normal_log<propto__>(centrality_mu, predictor, add(centrality_cov, diag_matrix(rep_vector(sigma, num_nodes)))));
            current_statement_begin__ = 21;
            lp_accum__.add(normal_log<propto__>(beta_fixed, 0, 1));
            current_statement_begin__ = 22;
            lp_accum__.add(normal_log<propto__>(sigma, 0, 1));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("beta_fixed");
        names__.push_back("sigma");
        names__.push_back("predictor");
        names__.push_back("centrality_pred");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(num_fixed);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(num_nodes);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(num_nodes);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_nodal_regression_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_fixed = in__.vector_constrain(num_fixed);
        size_t beta_fixed_j_1_max__ = num_fixed;
        for (size_t j_1__ = 0; j_1__ < beta_fixed_j_1_max__; ++j_1__) {
            vars__.push_back(beta_fixed(j_1__));
        }
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 15;
            validate_non_negative_index("predictor", "num_nodes", num_nodes);
            Eigen::Matrix<double, Eigen::Dynamic, 1> predictor(num_nodes);
            stan::math::initialize(predictor, DUMMY_VAR__);
            stan::math::fill(predictor, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 16;
            stan::math::assign(predictor, multiply(design_fixed, beta_fixed));
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t predictor_j_1_max__ = num_nodes;
                for (size_t j_1__ = 0; j_1__ < predictor_j_1_max__; ++j_1__) {
                    vars__.push_back(predictor(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 26;
            validate_non_negative_index("centrality_pred", "num_nodes", num_nodes);
            Eigen::Matrix<double, Eigen::Dynamic, 1> centrality_pred(num_nodes);
            stan::math::initialize(centrality_pred, DUMMY_VAR__);
            stan::math::fill(centrality_pred, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 27;
            stan::math::assign(centrality_pred, multi_normal_rng(predictor, add(centrality_cov, diag_matrix(rep_vector(sigma, num_nodes))), base_rng__));
            // validate, write generated quantities
            current_statement_begin__ = 26;
            size_t centrality_pred_j_1_max__ = num_nodes;
            for (size_t j_1__ = 0; j_1__ < centrality_pred_j_1_max__; ++j_1__) {
                vars__.push_back(centrality_pred(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_nodal_regression";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_fixed_j_1_max__ = num_fixed;
        for (size_t j_1__ = 0; j_1__ < beta_fixed_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_fixed" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t predictor_j_1_max__ = num_nodes;
            for (size_t j_1__ = 0; j_1__ < predictor_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "predictor" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t centrality_pred_j_1_max__ = num_nodes;
        for (size_t j_1__ = 0; j_1__ < centrality_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "centrality_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_fixed_j_1_max__ = num_fixed;
        for (size_t j_1__ = 0; j_1__ < beta_fixed_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_fixed" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t predictor_j_1_max__ = num_nodes;
            for (size_t j_1__ = 0; j_1__ < predictor_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "predictor" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t centrality_pred_j_1_max__ = num_nodes;
        for (size_t j_1__ = 0; j_1__ < centrality_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "centrality_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_nodal_regression_namespace::model_nodal_regression stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
