# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("binary_fixed", "binary_mixed", "count_fixed", "count_mixed", "duration_fixed", "duration_null", "dyadic_regression", "nodal_regression")

# load each stan module
Rcpp::loadModule("stan_fit4binary_fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4binary_mixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4count_fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4count_mixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4duration_fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4duration_null_mod", what = TRUE)
Rcpp::loadModule("stan_fit4dyadic_regression_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nodal_regression_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
